------------------
-- Pokémon Data --
------------------
CREATE TYPE pokemon_evolution_time_of_day AS ENUM (
    'day',
    'night'
);

CREATE TABLE languages (
    id integer PRIMARY KEY NOT NULL,
    iso639 text NOT NULL,
    iso3166 text NOT NULL,
    identifier text NOT NULL,
    official boolean NOT NULL
);

CREATE TABLE pokemon_species (
    id integer PRIMARY KEY NOT NULL,
    identifier text NOT NULL,
    is_legendary boolean NOT NULL,
    is_mythical boolean NOT NULL,
    is_ultra_beast boolean NOT NULL
);

CREATE TABLE pokemon_species_names (
    species_id integer NOT NULL REFERENCES pokemon_species (id) ON DELETE CASCADE,
    language_id integer NOT NULL REFERENCES languages (id) ON DELETE CASCADE,
    name text NOT NULL,
    genus text NULL,
    PRIMARY KEY (species_id, language_id)
);

CREATE TABLE pokemon_species_flavor_text (
    species_id integer NOT NULL REFERENCES pokemon_species (id) ON DELETE CASCADE,
    language_id integer NOT NULL REFERENCES languages (id) ON DELETE CASCADE,
    flavor_text text NOT NULL,
    PRIMARY KEY (species_id, language_id)
);

CREATE TABLE pokemon (
    id integer PRIMARY KEY NOT NULL,
    identifier text NOT NULL,
    species_id integer NOT NULL REFERENCES pokemon_species (id) ON DELETE CASCADE,
    height integer NOT NULL,
    weight integer NOT NULL,
    base_experience integer NOT NULL,
    is_default boolean NOT NULL
);

CREATE INDEX pokemon_species_id_idx ON pokemon (species_id);

CREATE TABLE evolution_triggers (
    id integer PRIMARY KEY NOT NULL,
    identifier text NOT NULL
);

CREATE TABLE items (
    id integer PRIMARY KEY NOT NULL,
    identifier text NOT NULL,
    cost integer NOT NULL
);

CREATE TABLE move_targets (
    id integer PRIMARY KEY NOT NULL,
    identifier text NOT NULL
);

CREATE TABLE damage_classes (
    id integer PRIMARY KEY NOT NULL,
    identifier text NOT NULL
);

CREATE TABLE types (
    id integer PRIMARY KEY NOT NULL,
    identifier text NOT NULL
);

CREATE TABLE move_effects (
    id integer PRIMARY KEY NOT NULL
);

CREATE TABLE moves (
    id integer PRIMARY KEY NOT NULL,
    identifier text NOT NULL,
    type_id integer NOT NULL REFERENCES types (id) ON DELETE CASCADE,
    power smallint NULL,
    pp smallint NULL,
    accuracy smallint NULL,
    priority smallint NOT NULL,
    target_id integer NOT NULL REFERENCES move_targets (id) ON DELETE CASCADE,
    damage_class_id integer NOT NULL REFERENCES damage_classes (id) ON DELETE CASCADE,
    effect_id integer NOT NULL REFERENCES move_effects (id) ON DELETE CASCADE,
    effect_chance integer NULL
);

CREATE TABLE pokemon_evolutions (
    id integer PRIMARY KEY NOT NULL,
    evolved_species_id integer NOT NULL REFERENCES pokemon_species (id) ON DELETE CASCADE,
    evolution_trigger_id integer NOT NULL REFERENCES evolution_triggers (id) ON DELETE CASCADE,
    trigger_item_id integer NULL REFERENCES items (id) ON DELETE CASCADE,
    minimum_level integer NULL,
    held_item_id integer NULL REFERENCES items (id) ON DELETE CASCADE,
    time_of_day pokemon_evolution_time_of_day NULL,
    known_move_id integer NULL REFERENCES moves (id) ON DELETE CASCADE,
    known_move_type_id integer NULL REFERENCES types (id) ON DELETE CASCADE,
    minimum_happiness integer NULL
);

CREATE INDEX pokemon_evolutions_evolved_species_id_idx ON pokemon_evolutions (evolved_species_id);

CREATE TABLE pokemon_types (
    pokemon_id integer NOT NULL REFERENCES pokemon (id) ON DELETE CASCADE,
    type_id integer NOT NULL REFERENCES types (id) ON DELETE CASCADE,
    PRIMARY KEY (pokemon_id, type_id)
);

CREATE TABLE pokemon_forms (
    id integer PRIMARY KEY NOT NULL,
    identifier text NOT NULL,
    form_identifier text NULL,
    pokemon_id integer NOT NULL REFERENCES pokemon (id) ON DELETE CASCADE,
    is_default boolean NOT NULL,
    is_mega boolean NOT NULL,
    enabled boolean NOT NULL,
    allow_catch boolean NOT NULL,
    allow_redeem boolean NOT NULL
);

CREATE INDEX pokemon_forms_pokemon_id_idx ON pokemon_forms (pokemon_id);

CREATE TABLE pokemon_form_names (
    form_id integer NOT NULL REFERENCES pokemon_forms (id) ON DELETE CASCADE,
    language_id integer NOT NULL REFERENCES languages (id) ON DELETE CASCADE,
    form_name text NULL,
    pokemon_name text NULL,
    PRIMARY KEY (form_id, language_id)
);

------------------
-- Pokétwo Data --
------------------
CREATE TYPE pokemon_order AS ENUM (
    'name',
    'number',
    'pokedex',
    'iv'
);

CREATE TABLE users (
    id bigint PRIMARY KEY NOT NULL,
    joined_at timestamptz NOT NULL DEFAULT now(),
    suspended boolean NOT NULL DEFAULT FALSE,
    pokemon_sort_order pokemon_order NOT NULL DEFAULT 'number'
);

CREATE TABLE caught_pokemon (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    form_id integer NOT NULL REFERENCES pokemon_forms (id) ON DELETE CASCADE,
    iv_hp smallint NOT NULL,
    iv_atk smallint NOT NULL,
    iv_defn smallint NOT NULL,
    iv_satk smallint NOT NULL,
    iv_sdef smallint NOT NULL,
    iv_spd smallint NOT NULL,
    iv_total smallint GENERATED ALWAYS AS (iv_hp + iv_atk + iv_defn + iv_satk + iv_sdef + iv_spd) STORED,
    nickname text NULL,
    favorite boolean NOT NULL DEFAULT FALSE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX caught_pokemon_user_id_idx ON caught_pokemon (user_id);

ALTER TABLE users
    ADD COLUMN selected_pokemon_id integer NULL REFERENCES caught_pokemon (id) ON DELETE SET NULL;

