create type "public"."pokemon_evolution_time_of_day" as enum ('day', 'night');

create type "public"."pokemon_order" as enum ('name', 'number', 'pokedex', 'iv');

create table "public"."caught_pokemon" (
    "id" integer generated by default as identity not null,
    "form_id" integer not null,
    "iv_hp" smallint not null,
    "iv_atk" smallint not null,
    "iv_defn" smallint not null,
    "iv_satk" smallint not null,
    "iv_sdef" smallint not null,
    "iv_spd" smallint not null,
    "iv_total" smallint generated always as ((((((iv_hp + iv_atk) + iv_defn) + iv_satk) + iv_sdef) + iv_spd)) stored,
    "nickname" text,
    "favorite" boolean not null default false,
    "user_id" bigint not null
);


create table "public"."damage_classes" (
    "id" integer not null,
    "identifier" text not null
);


create table "public"."evolution_triggers" (
    "id" integer not null,
    "identifier" text not null
);


create table "public"."items" (
    "id" integer not null,
    "identifier" text not null,
    "cost" integer not null
);


create table "public"."languages" (
    "id" integer not null,
    "iso639" integer not null,
    "iso3166" integer not null,
    "identifier" text not null,
    "official" boolean not null
);


create table "public"."move_effects" (
    "id" integer not null
);


create table "public"."move_targets" (
    "id" integer not null,
    "identifier" text not null
);


create table "public"."moves" (
    "id" integer not null,
    "identifier" text not null,
    "type_id" integer not null,
    "power" smallint,
    "pp" smallint,
    "accuracy" smallint,
    "priority" smallint not null,
    "target_id" integer not null,
    "damage_class_id" integer not null,
    "effect_id" integer not null,
    "effect_chance" integer
);


create table "public"."pokemon" (
    "id" integer not null,
    "identifier" text not null,
    "species_id" integer not null,
    "height" integer not null,
    "weight" integer not null,
    "base_experience" integer not null,
    "is_default" boolean not null
);


create table "public"."pokemon_evolutions" (
    "id" integer not null,
    "evolved_species_id" integer not null,
    "evolution_trigger_id" integer not null,
    "trigger_item_id" integer,
    "minimum_level" integer,
    "held_item_id" integer,
    "time_of_day" pokemon_evolution_time_of_day,
    "known_move_id" integer,
    "known_move_type_id" integer,
    "minimum_happiness" integer
);


create table "public"."pokemon_form_names" (
    "form_id" integer not null,
    "language_id" integer not null,
    "form_name" text,
    "pokemon_name" text
);


create table "public"."pokemon_forms" (
    "id" integer not null,
    "identifier" text not null,
    "form_identifier" text,
    "pokemon_id" integer not null,
    "is_default" boolean not null,
    "is_mega" boolean not null,
    "enabled" boolean not null,
    "allow_catch" boolean not null,
    "allow_redeem" boolean not null
);


create table "public"."pokemon_species" (
    "id" integer not null,
    "identifier" text not null,
    "is_legendary" boolean not null,
    "is_mythical" boolean not null,
    "is_ultra_beast" boolean not null
);


create table "public"."pokemon_species_flavor_text" (
    "species_id" integer not null,
    "language_id" integer not null,
    "flavor_text" text not null
);


create table "public"."pokemon_species_names" (
    "species_id" integer not null,
    "language_id" integer not null,
    "name" text not null,
    "genus" text not null
);


create table "public"."pokemon_types" (
    "pokemon_id" integer not null,
    "type_id" integer not null
);


create table "public"."types" (
    "id" integer not null,
    "identifier" text not null
);


create table "public"."users" (
    "id" bigint not null,
    "joined_at" timestamp with time zone not null default now(),
    "suspended" boolean not null default false,
    "pokemon_sort_order" pokemon_order not null default 'number'::pokemon_order,
    "selected_pokemon_id" integer
);


CREATE UNIQUE INDEX caught_pokemon_pkey ON public.caught_pokemon USING btree (id);

CREATE INDEX caught_pokemon_user_id_idx ON public.caught_pokemon USING btree (user_id);

CREATE UNIQUE INDEX damage_classes_pkey ON public.damage_classes USING btree (id);

CREATE UNIQUE INDEX evolution_triggers_pkey ON public.evolution_triggers USING btree (id);

CREATE UNIQUE INDEX items_pkey ON public.items USING btree (id);

CREATE UNIQUE INDEX languages_pkey ON public.languages USING btree (id);

CREATE UNIQUE INDEX move_effects_pkey ON public.move_effects USING btree (id);

CREATE UNIQUE INDEX move_targets_pkey ON public.move_targets USING btree (id);

CREATE UNIQUE INDEX moves_pkey ON public.moves USING btree (id);

CREATE INDEX pokemon_evolutions_evolved_species_id_idx ON public.pokemon_evolutions USING btree (evolved_species_id);

CREATE UNIQUE INDEX pokemon_evolutions_pkey ON public.pokemon_evolutions USING btree (id);

CREATE UNIQUE INDEX pokemon_forms_pkey ON public.pokemon_forms USING btree (id);

CREATE INDEX pokemon_forms_pokemon_id_idx ON public.pokemon_forms USING btree (pokemon_id);

CREATE UNIQUE INDEX pokemon_pkey ON public.pokemon USING btree (id);

CREATE UNIQUE INDEX pokemon_species_flavor_text_pkey ON public.pokemon_species_flavor_text USING btree (species_id, language_id);

CREATE INDEX pokemon_species_id_idx ON public.pokemon USING btree (species_id);

CREATE UNIQUE INDEX pokemon_species_names_pkey ON public.pokemon_species_names USING btree (species_id, language_id);

CREATE UNIQUE INDEX pokemon_species_pkey ON public.pokemon_species USING btree (id);

CREATE UNIQUE INDEX pokemon_types_pkey ON public.pokemon_types USING btree (pokemon_id, type_id);

CREATE UNIQUE INDEX types_pkey ON public.types USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."caught_pokemon" add constraint "caught_pokemon_pkey" PRIMARY KEY using index "caught_pokemon_pkey";

alter table "public"."damage_classes" add constraint "damage_classes_pkey" PRIMARY KEY using index "damage_classes_pkey";

alter table "public"."evolution_triggers" add constraint "evolution_triggers_pkey" PRIMARY KEY using index "evolution_triggers_pkey";

alter table "public"."items" add constraint "items_pkey" PRIMARY KEY using index "items_pkey";

alter table "public"."languages" add constraint "languages_pkey" PRIMARY KEY using index "languages_pkey";

alter table "public"."move_effects" add constraint "move_effects_pkey" PRIMARY KEY using index "move_effects_pkey";

alter table "public"."move_targets" add constraint "move_targets_pkey" PRIMARY KEY using index "move_targets_pkey";

alter table "public"."moves" add constraint "moves_pkey" PRIMARY KEY using index "moves_pkey";

alter table "public"."pokemon" add constraint "pokemon_pkey" PRIMARY KEY using index "pokemon_pkey";

alter table "public"."pokemon_evolutions" add constraint "pokemon_evolutions_pkey" PRIMARY KEY using index "pokemon_evolutions_pkey";

alter table "public"."pokemon_forms" add constraint "pokemon_forms_pkey" PRIMARY KEY using index "pokemon_forms_pkey";

alter table "public"."pokemon_species" add constraint "pokemon_species_pkey" PRIMARY KEY using index "pokemon_species_pkey";

alter table "public"."pokemon_species_flavor_text" add constraint "pokemon_species_flavor_text_pkey" PRIMARY KEY using index "pokemon_species_flavor_text_pkey";

alter table "public"."pokemon_species_names" add constraint "pokemon_species_names_pkey" PRIMARY KEY using index "pokemon_species_names_pkey";

alter table "public"."pokemon_types" add constraint "pokemon_types_pkey" PRIMARY KEY using index "pokemon_types_pkey";

alter table "public"."types" add constraint "types_pkey" PRIMARY KEY using index "types_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."caught_pokemon" add constraint "caught_pokemon_form_id_fkey" FOREIGN KEY (form_id) REFERENCES pokemon_forms(id) ON DELETE CASCADE;

alter table "public"."caught_pokemon" add constraint "caught_pokemon_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table "public"."moves" add constraint "moves_damage_class_id_fkey" FOREIGN KEY (damage_class_id) REFERENCES damage_classes(id) ON DELETE CASCADE;

alter table "public"."moves" add constraint "moves_effect_id_fkey" FOREIGN KEY (effect_id) REFERENCES move_effects(id) ON DELETE CASCADE;

alter table "public"."moves" add constraint "moves_target_id_fkey" FOREIGN KEY (target_id) REFERENCES move_targets(id) ON DELETE CASCADE;

alter table "public"."moves" add constraint "moves_type_id_fkey" FOREIGN KEY (type_id) REFERENCES types(id) ON DELETE CASCADE;

alter table "public"."pokemon" add constraint "pokemon_species_id_fkey" FOREIGN KEY (species_id) REFERENCES pokemon_species(id) ON DELETE CASCADE;

alter table "public"."pokemon_evolutions" add constraint "pokemon_evolutions_evolution_trigger_id_fkey" FOREIGN KEY (evolution_trigger_id) REFERENCES evolution_triggers(id) ON DELETE CASCADE;

alter table "public"."pokemon_evolutions" add constraint "pokemon_evolutions_evolved_species_id_fkey" FOREIGN KEY (evolved_species_id) REFERENCES pokemon_species(id) ON DELETE CASCADE;

alter table "public"."pokemon_evolutions" add constraint "pokemon_evolutions_held_item_id_fkey" FOREIGN KEY (held_item_id) REFERENCES items(id) ON DELETE CASCADE;

alter table "public"."pokemon_evolutions" add constraint "pokemon_evolutions_known_move_id_fkey" FOREIGN KEY (known_move_id) REFERENCES moves(id) ON DELETE CASCADE;

alter table "public"."pokemon_evolutions" add constraint "pokemon_evolutions_known_move_type_id_fkey" FOREIGN KEY (known_move_type_id) REFERENCES types(id) ON DELETE CASCADE;

alter table "public"."pokemon_evolutions" add constraint "pokemon_evolutions_trigger_item_id_fkey" FOREIGN KEY (trigger_item_id) REFERENCES items(id) ON DELETE CASCADE;

alter table "public"."pokemon_form_names" add constraint "pokemon_form_names_form_id_fkey" FOREIGN KEY (form_id) REFERENCES pokemon_forms(id) ON DELETE CASCADE;

alter table "public"."pokemon_form_names" add constraint "pokemon_form_names_language_id_fkey" FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE CASCADE;

alter table "public"."pokemon_forms" add constraint "pokemon_forms_pokemon_id_fkey" FOREIGN KEY (pokemon_id) REFERENCES pokemon(id) ON DELETE CASCADE;

alter table "public"."pokemon_species_flavor_text" add constraint "pokemon_species_flavor_text_language_id_fkey" FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE CASCADE;

alter table "public"."pokemon_species_flavor_text" add constraint "pokemon_species_flavor_text_species_id_fkey" FOREIGN KEY (species_id) REFERENCES pokemon_species(id) ON DELETE CASCADE;

alter table "public"."pokemon_species_names" add constraint "pokemon_species_names_language_id_fkey" FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE CASCADE;

alter table "public"."pokemon_species_names" add constraint "pokemon_species_names_species_id_fkey" FOREIGN KEY (species_id) REFERENCES pokemon_species(id) ON DELETE CASCADE;

alter table "public"."pokemon_types" add constraint "pokemon_types_pokemon_id_fkey" FOREIGN KEY (pokemon_id) REFERENCES pokemon(id) ON DELETE CASCADE;

alter table "public"."pokemon_types" add constraint "pokemon_types_type_id_fkey" FOREIGN KEY (type_id) REFERENCES types(id) ON DELETE CASCADE;

alter table "public"."users" add constraint "users_selected_pokemon_id_fkey" FOREIGN KEY (selected_pokemon_id) REFERENCES caught_pokemon(id) ON DELETE SET NULL;

